# Uncomment the next line to define a global platform for your project

target 'Bityo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'
  
  pod "IQKeyboardManagerSwift"
  pod "WARangeSlider"
  pod 'SDWebImage'
  pod 'SwipeCellKit'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'UITextView+Placeholder'
  pod 'DropDown'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  #  pod 'PinterestLayout'
  pod 'FacebookShare'
  pod 'Google/SignIn'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.5'
  pod 'JDStatusBarNotification'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TwitterKit'

end

